### PR TITLE
Revise and define div/@subtype values

### PR DESCRIPTION
**Pull request by WaxCylinderRevival**
Re: issue #299

### CODE REVIEW

**Comment by joewiz** [comment]
@WaxCylinderRevival Re your comment in https://github.com/HistoryAtState/frus/pull/300/commits/747a8ba2039d7846a96d56643870cf8484e2a70a, I have no objection to merging the `chapter-introduction` subtype value into `editorial-note`, as these sections are authored by the editor. Their divs' `@type` of `section` distinguishes these from formal editorial notes, i.e., the ones that are given document numbers.

**Comment by WaxCylinderRevival** [comment]
@joewiz, agreed.  Wonderful!

**Comment by joewiz** [comment]
@WaxCylinderRevival Is work ongoing in this branch, or is it ready for review?

**Comment by WaxCylinderRevival** [comment]
@joewiz, ready for you!  I folded in the changes you made to the master yesterday so it would hopefully be easier for you to review.

**Review by joewiz — APPROVED** [review]

**Comment by joewiz** [comment]
@WaxCylinderRevival Looks good. Many thanks! 

Closes #299

**Comment by WaxCylinderRevival** [comment]
Terrific!  Thanks, @joewiz

**Pull request merged**
